/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// CveAllowlist The CVE Allowlist for system or project
type CveAllowlist struct {
	// ID of the allowlist
	Id int32 `json:"id,omitempty"`
	// ID of the project which the allowlist belongs to.  For system level allowlist this attribute is zero.
	ProjectId int32 `json:"project_id,omitempty"`
	// the time for expiration of the allowlist, in the form of seconds since epoch.  This is an optional attribute, if it's not set the CVE allowlist does not expire.
	ExpiresAt *int32 `json:"expires_at,omitempty"`
	Items []CveAllowlistItem `json:"items,omitempty"`
	// The creation time of the allowlist.
	CreationTime time.Time `json:"creation_time,omitempty"`
	// The update time of the allowlist.
	UpdateTime time.Time `json:"update_time,omitempty"`
}
