/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// RegistryInfo The registry info contains the base info and capability declarations of the registry
type RegistryInfo struct {
	// The registry type
	Type string `json:"type,omitempty"`
	// The description
	Description string `json:"description,omitempty"`
	// The filters that the registry supports
	SupportedResourceFilters []FilterStyle `json:"supported_resource_filters,omitempty"`
	// The triggers that the registry supports
	SupportedTriggers []string `json:"supported_triggers,omitempty"`
}
