/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PasswordReq struct for PasswordReq
type PasswordReq struct {
	// The user's existing password.
	OldPassword string `json:"old_password,omitempty"`
	// New password for marking as to be updated.
	NewPassword string `json:"new_password,omitempty"`
}
