/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// ScheduleObj struct for ScheduleObj
type ScheduleObj struct {
	// The schedule type. The valid values are 'Hourly', 'Daily', 'Weekly', 'Custom', 'Manual' and 'None'. 'Manual' means to trigger it right away and 'None' means to cancel the schedule. 
	Type string `json:"type,omitempty"`
	// A cron expression, a time-based job scheduler.
	Cron string `json:"cron,omitempty"`
	// The next time to schedule to run the job.
	NextScheduledTime time.Time `json:"next_scheduled_time,omitempty"`
}
