/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package harbor
// Pet struct for Pet
type Pet struct {
	// 宠物ID编号
	Id int64 `json:"id"`
	Category Category `json:"category"`
	// 名称
	Name string `json:"name"`
	// 照片URL
	PhotoUrls []string `json:"photoUrls"`
	// 标签
	Tags []Tag `json:"tags"`
	// 宠物销售状态
	Status string `json:"status"`
}
