/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Metadata struct for Metadata
type Metadata struct {
	// id
	Id string `json:"id,omitempty"`
	// name
	Name string `json:"name,omitempty"`
	// icon
	Icon string `json:"icon,omitempty"`
	// maintainers
	Maintainers []string `json:"maintainers,omitempty"`
	// version
	Version string `json:"version,omitempty"`
	// source
	Source string `json:"source,omitempty"`
}
