/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UserSearchRespItem struct for UserSearchRespItem
type UserSearchRespItem struct {
	// The ID of the user.
	UserId int32 `json:"user_id,omitempty"`
	Username string `json:"username,omitempty"`
}
