/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package harbor
// CveAllowlistItem The item in CVE allowlist
type CveAllowlistItem struct {
	// The ID of the CVE, such as \"CVE-2019-10164\"
	CveId string `json:"cve_id,omitempty"`
}
