/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package harbor
// RobotCreateV1 struct for RobotCreateV1
type RobotCreateV1 struct {
	// The name of robot account
	Name string `json:"name,omitempty"`
	// The description of robot account
	Description string `json:"description,omitempty"`
	// The expiration time on or after which the JWT MUST NOT be accepted for processing.
	ExpiresAt int32 `json:"expires_at,omitempty"`
	// The permission of robot account
	Access []Access `json:"access,omitempty"`
}
