/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package harbor
// RetentionRuleParamMetadata rule param
type RetentionRuleParamMetadata struct {
	Type string `json:"type,omitempty"`
	Unit string `json:"unit,omitempty"`
	Required bool `json:"required,omitempty"`
}
