/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Scanner struct for Scanner
type Scanner struct {
	// Name of the scanner
	Name string `json:"name,omitempty"`
	// Name of the scanner provider
	Vendor string `json:"vendor,omitempty"`
	// Version of the scanner adapter
	Version string `json:"version,omitempty"`
}
