/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package harbor
// ScanDataExportExecutionList The list of scan data export executions
type ScanDataExportExecutionList struct {
	// The list of scan data export executions
	Items []ScanDataExportExecution `json:"items,omitempty"`
}
