/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package harbor
// ScannerRegistrationSettings struct for ScannerRegistrationSettings
type ScannerRegistrationSettings struct {
	// The name of this registration
	Name string `json:"name"`
	// A base URL of the scanner adapter.
	Url string `json:"url"`
	// Specify what authentication approach is adopted for the HTTP communications. Supported types Basic\", \"Bearer\" and api key header \"X-ScannerAdapter-API-Key\" 
	Auth string `json:"auth,omitempty"`
	// An optional value of the HTTP Authorization header sent with each request to the Scanner Adapter API. 
	AccessCredential string `json:"access_credential,omitempty"`
}
