/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// RetentionRuleTrigger struct for RetentionRuleTrigger
type RetentionRuleTrigger struct {
	Kind string `json:"kind,omitempty"`
	Settings map[string]interface{} `json:"settings,omitempty"`
	References map[string]interface{} `json:"references,omitempty"`
}
