/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package harbor
// Errors The error array that describe the errors got during the handling of request
type Errors struct {
	Errors []Error `json:"errors,omitempty"`
}
