/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// WebhookTargetObject The webhook policy target object.
type WebhookTargetObject struct {
	// The webhook target notify type.
	Type string `json:"type,omitempty"`
	// The webhook target address.
	Address string `json:"address,omitempty"`
	// The webhook auth header.
	AuthHeader string `json:"auth_header,omitempty"`
	// Whether or not to skip cert verify.
	SkipCertVerify bool `json:"skip_cert_verify,omitempty"`
}
