/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// StartReplicationExecution struct for StartReplicationExecution
type StartReplicationExecution struct {
	// The ID of policy that the execution belongs to.
	PolicyId int64 `json:"policy_id,omitempty"`
}
