/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package harbor
// RetentionRule struct for RetentionRule
type RetentionRule struct {
	Id int32 `json:"id,omitempty"`
	Priority int32 `json:"priority,omitempty"`
	Disabled bool `json:"disabled,omitempty"`
	Action string `json:"action,omitempty"`
	Template string `json:"template,omitempty"`
	Params map[string]map[string]interface{} `json:"params,omitempty"`
	TagSelectors []RetentionSelector `json:"tag_selectors,omitempty"`
	ScopeSelectors map[string][]RetentionSelector `json:"scope_selectors,omitempty"`
}
