/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// ScanDataExportExecution The replication execution
type ScanDataExportExecution struct {
	// The ID of the execution
	Id int32 `json:"id,omitempty"`
	// The ID if the user triggering the export job
	UserId int32 `json:"user_id,omitempty"`
	// The status of the execution
	Status string `json:"status,omitempty"`
	// The trigger mode
	Trigger string `json:"trigger,omitempty"`
	// The start time
	StartTime time.Time `json:"start_time,omitempty"`
	// The end time
	EndTime time.Time `json:"end_time,omitempty"`
	// The status text
	StatusText string `json:"status_text,omitempty"`
	// The name of the user triggering the job
	UserName string `json:"user_name,omitempty"`
	// Indicates whether the export artifact is present in registry
	FilePresent bool `json:"file_present,omitempty"`
}
