/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package harbor
// RetentionPolicy retention policy
type RetentionPolicy struct {
	Id int64 `json:"id,omitempty"`
	Algorithm string `json:"algorithm,omitempty"`
	Rules []RetentionRule `json:"rules,omitempty"`
	Trigger RetentionRuleTrigger `json:"trigger,omitempty"`
	Scope RetentionPolicyScope `json:"scope,omitempty"`
}
