/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ReplicationTrigger struct for ReplicationTrigger
type ReplicationTrigger struct {
	// The replication policy trigger type. The valid values are manual, event_based and scheduled.
	Type string `json:"type,omitempty"`
	TriggerSettings ReplicationTriggerSettings `json:"trigger_settings,omitempty"`
}
