/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package harbor
// RobotCreate The request for robot account creation.
type RobotCreate struct {
	// The name of the tag
	Name string `json:"name,omitempty"`
	// The description of the robot
	Description string `json:"description,omitempty"`
	// The secret of the robot
	Secret string `json:"secret,omitempty"`
	// The level of the robot, project or system
	Level string `json:"level,omitempty"`
	// The disable status of the robot
	Disable bool `json:"disable,omitempty"`
	// The duration of the robot in days
	Duration int64 `json:"duration,omitempty"`
	Permissions []RobotPermission `json:"permissions,omitempty"`
}
