/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ProjectDeletable struct for ProjectDeletable
type ProjectDeletable struct {
	// Whether the project can be deleted.
	Deletable bool `json:"deletable,omitempty"`
	// The detail message when the project can not be deleted.
	Message string `json:"message,omitempty"`
}
