/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package harbor
// RetentionSelectorMetadata retention selector
type RetentionSelectorMetadata struct {
	DisplayText string `json:"display_text,omitempty"`
	Kind string `json:"kind,omitempty"`
	Decorations []string `json:"decorations,omitempty"`
}
