/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package harbor
// ChartVersionAllOf struct for ChartVersionAllOf
type ChartVersionAllOf struct {
	// The created time of the chart entry
	Created string `json:"created,omitempty"`
	// A flag to indicate if the chart entry is removed
	Removed bool `json:"removed,omitempty"`
	// The digest value of the chart entry
	Digest string `json:"digest,omitempty"`
	// The urls of the chart entry
	Urls []string `json:"urls,omitempty"`
}
