/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ScanDataExportJob The metadata associated with the scan data export job
type ScanDataExportJob struct {
	// The id of the scan data export job
	Id int64 `json:"id,omitempty"`
}
