/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// RegistryUpdate struct for RegistryUpdate
type RegistryUpdate struct {
	// The registry name.
	Name *string `json:"name,omitempty"`
	// Description of the registry.
	Description *string `json:"description,omitempty"`
	// The registry URL.
	Url *string `json:"url,omitempty"`
	// Credential type of the registry, e.g. 'basic'.
	CredentialType *string `json:"credential_type,omitempty"`
	// The registry access key.
	AccessKey *string `json:"access_key,omitempty"`
	// The registry access secret.
	AccessSecret *string `json:"access_secret,omitempty"`
	// Whether or not the certificate will be verified when Harbor tries to access the server.
	Insecure *bool `json:"insecure,omitempty"`
}
