/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// FilterStyle The style of the resource filter
type FilterStyle struct {
	// The filter type
	Type string `json:"type,omitempty"`
	// The filter style
	Style string `json:"style,omitempty"`
	// The filter values
	Values []string `json:"values,omitempty"`
}
