/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// Accessory The accessory of the artifact
type Accessory struct {
	// The ID of the accessory
	Id int64 `json:"id,omitempty"`
	// The artifact id of the accessory
	ArtifactId int64 `json:"artifact_id,omitempty"`
	// The subject artifact id of the accessory
	SubjectArtifactId int64 `json:"subject_artifact_id,omitempty"`
	// The artifact size of the accessory
	Size int64 `json:"size,omitempty"`
	// The artifact digest of the accessory
	Digest string `json:"digest,omitempty"`
	// The artifact size of the accessory
	Type string `json:"type,omitempty"`
	// The icon of the accessory
	Icon string `json:"icon,omitempty"`
	// The creation time of the accessory
	CreationTime time.Time `json:"creation_time,omitempty"`
}
