/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// RetentionRuleMetadata the tag retention rule metadata
type RetentionRuleMetadata struct {
	// rule id
	RuleTemplate string `json:"rule_template,omitempty"`
	// rule display text
	DisplayText string `json:"display_text,omitempty"`
	// rule action
	Action string `json:"action,omitempty"`
	// rule params
	Params []RetentionRuleParamMetadata `json:"params,omitempty"`
}
