/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package harbor
// Error a model for all the error response coming from harbor
type Error struct {
	// The error code
	Code string `json:"code,omitempty"`
	// The error message
	Message string `json:"message,omitempty"`
}
