/*
 * harbor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package harbor
// ProjectScanner struct for ProjectScanner
type ProjectScanner struct {
	// The identifier of the scanner registration
	Uuid string `json:"uuid"`
}
